# Your API Keys and Form ID
GEMINI_API_KEY = "AIzaSyCqq1qXYeKFgAqJmTdii8dKBdz7dsSjKys"
JOTFORM_API_KEY = "61d1e5d506601fcb610dced3c417176e"
JOTFORM_FORM_ID = "201810973343553"

# The mapping between the AI's data and your Jotform fields
[JOTFORM_FIELD_MAPPING]
respondentName = "name" # Replace with your actual unique name
age = "age"
incidentDate = "dateamp7"
incidentTime = "dateamp7"
violationType = "typeOf13"
eventSummary = "caseDescription"
contactDetails = "phoneNumber"
sexualOrientation = "sexualOrientation"
genderIdentity = "genderIdentity"
perpetrator = "perpetrators"
arrestCharges = "ifDetainedarrested"
caseAssignedTo = "caseAssigned"
caseReferredBy = "caseReferred"
referralReceivedBy = "referralReceived"
evidenceNotes = "descriptionOf"
